// Complete Course Catalog - 74 Courses

export interface Course {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  categorySlug: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  duration: string;
  lessons: number;
  projects: number;
  rating: number;
  reviews: number;
  students: number;
  instructor: string;
  image: string;
  tags: string[];
  topics: string[];
  featured?: boolean;
}

export interface Category {
  name: string;
  slug: string;
  icon: string;
  courseCount: number;
}

export const categories: Category[] = [
  { name: 'Frontend Development', slug: 'frontend', icon: '🎨', courseCount: 11 },
  { name: 'Backend Development', slug: 'backend', icon: '⚙️', courseCount: 9 },
  { name: 'Database Technologies', slug: 'database', icon: '🗄️', courseCount: 7 },
  { name: 'Blockchain & Web3', slug: 'blockchain', icon: '⛓️', courseCount: 11 },
  { name: 'Mobile Development', slug: 'mobile', icon: '📱', courseCount: 4 },
  { name: 'DevOps & Cloud', slug: 'devops', icon: '☁️', courseCount: 9 },
  { name: 'Data Science & AI', slug: 'data-science', icon: '🤖', courseCount: 5 },
  { name: 'Programming Fundamentals', slug: 'fundamentals', icon: '📚', courseCount: 6 },
  { name: 'Testing & QA', slug: 'testing', icon: '✅', courseCount: 4 },
  { name: 'Specialized Skills', slug: 'specialized', icon: '🎯', courseCount: 8 },
];

export const courses: Course[] = [
  // Frontend Development (11 courses)
  {
    id: 'html5-fundamentals',
    slug: 'html5-fundamentals',
    title: 'HTML5 Complete Guide',
    description: 'Master HTML5 structure, semantics, forms, accessibility, and modern APIs for building robust web foundations.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Beginner',
    duration: '8 hours',
    lessons: 45,
    projects: 3,
    rating: 4.9,
    reviews: 2340,
    students: 45230,
    instructor: 'Sarah Chen',
    image: '/images/courses/html5.jpg',
    tags: ['HTML5', 'Web Basics', 'Accessibility'],
    topics: ['HTML5 Structure', 'Semantic Elements', 'Forms & Validation', 'Accessibility', 'HTML5 APIs'],
    featured: true,
  },
  {
    id: 'css3-mastery',
    slug: 'css3-mastery',
    title: 'CSS3 Mastery',
    description: 'Deep dive into CSS3 layouts, flexbox, grid, animations, responsive design, and preprocessors like SASS/SCSS.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Intermediate',
    duration: '12 hours',
    lessons: 65,
    projects: 4,
    rating: 4.8,
    reviews: 1890,
    students: 38450,
    instructor: 'Marcus Williams',
    image: '/images/courses/css3.jpg',
    tags: ['CSS3', 'Flexbox', 'Grid', 'SASS'],
    topics: ['CSS Layouts', 'Flexbox', 'CSS Grid', 'Animations', 'Responsive Design', 'SASS/SCSS'],
  },
  {
    id: 'javascript-es6-plus',
    slug: 'javascript-es6-plus',
    title: 'JavaScript ES6+ Complete Guide',
    description: 'Master modern JavaScript with ES6+ features, DOM manipulation, async programming, and API integration.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Intermediate',
    duration: '15 hours',
    lessons: 80,
    projects: 5,
    rating: 4.9,
    reviews: 3450,
    students: 62340,
    instructor: 'Alex Rodriguez',
    image: '/images/courses/javascript.jpg',
    tags: ['JavaScript', 'ES6+', 'Async', 'APIs'],
    topics: ['ES6+ Features', 'DOM Manipulation', 'Async/Await', 'Promises', 'API Integration'],
    featured: true,
  },
  {
    id: 'typescript-fundamentals',
    slug: 'typescript-fundamentals',
    title: 'TypeScript Fundamentals',
    description: 'Learn TypeScript types, interfaces, generics, decorators, and integration with React for type-safe development.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 55,
    projects: 3,
    rating: 4.8,
    reviews: 1560,
    students: 28900,
    instructor: 'Emma Thompson',
    image: '/images/courses/typescript.jpg',
    tags: ['TypeScript', 'Types', 'React'],
    topics: ['Types', 'Interfaces', 'Generics', 'Decorators', 'TypeScript with React'],
  },
  {
    id: 'react-complete',
    slug: 'react-complete',
    title: 'React.js Complete Course',
    description: 'Build modern React applications with hooks, state management, routing, Context API, and React Query.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Intermediate',
    duration: '18 hours',
    lessons: 95,
    projects: 6,
    rating: 4.9,
    reviews: 4230,
    students: 78560,
    instructor: 'David Kim',
    image: '/images/courses/react.jpg',
    tags: ['React', 'Hooks', 'State Management'],
    topics: ['Components', 'Hooks', 'State Management', 'Routing', 'Context API', 'React Query'],
    featured: true,
  },
  {
    id: 'nextjs-fullstack',
    slug: 'nextjs-fullstack',
    title: 'Next.js Full-Stack Development',
    description: 'Master Next.js with server-side rendering, static generation, API routes, and the new app router.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Advanced',
    duration: '14 hours',
    lessons: 70,
    projects: 4,
    rating: 4.8,
    reviews: 1890,
    students: 34560,
    instructor: 'Lisa Park',
    image: '/images/courses/nextjs.jpg',
    tags: ['Next.js', 'SSR', 'Full-Stack'],
    topics: ['Server-Side Rendering', 'Static Generation', 'API Routes', 'App Router'],
  },
  {
    id: 'vuejs-complete',
    slug: 'vuejs-complete',
    title: 'Vue.js 3 Complete Guide',
    description: 'Learn Vue 3 composition API, Vuex/Pinia state management, and Vue Router for building reactive applications.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Intermediate',
    duration: '12 hours',
    lessons: 60,
    projects: 4,
    rating: 4.7,
    reviews: 1230,
    students: 24560,
    instructor: 'Michael Zhang',
    image: '/images/courses/vuejs.jpg',
    tags: ['Vue.js', 'Composition API', 'Pinia'],
    topics: ['Vue 3 Composition API', 'Vuex/Pinia', 'Vue Router'],
  },
  {
    id: 'angular-fundamentals',
    slug: 'angular-fundamentals',
    title: 'Angular Fundamentals',
    description: 'Build enterprise applications with Angular components, services, RxJS, and TypeScript integration.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 75,
    projects: 4,
    rating: 4.6,
    reviews: 980,
    students: 19870,
    instructor: 'Jennifer Brown',
    image: '/images/courses/angular.jpg',
    tags: ['Angular', 'RxJS', 'TypeScript'],
    topics: ['Components', 'Services', 'RxJS', 'TypeScript Integration'],
  },
  {
    id: 'tailwind-css',
    slug: 'tailwind-css',
    title: 'Tailwind CSS Mastery',
    description: 'Master utility-first CSS with Tailwind, responsive design patterns, and customization techniques.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Beginner',
    duration: '6 hours',
    lessons: 35,
    projects: 3,
    rating: 4.9,
    reviews: 2150,
    students: 42340,
    instructor: 'Chris Anderson',
    image: '/images/courses/tailwind.jpg',
    tags: ['Tailwind', 'CSS', 'Utility-First'],
    topics: ['Utility-First CSS', 'Responsive Design', 'Customization'],
  },
  {
    id: 'bootstrap-5',
    slug: 'bootstrap-5',
    title: 'Bootstrap 5 Complete',
    description: 'Learn Bootstrap 5 grid system, components, responsive utilities, and build professional layouts.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Beginner',
    duration: '5 hours',
    lessons: 30,
    projects: 2,
    rating: 4.5,
    reviews: 890,
    students: 18760,
    instructor: 'Rachel Green',
    image: '/images/courses/bootstrap.jpg',
    tags: ['Bootstrap', 'CSS Framework', 'Responsive'],
    topics: ['Grid System', 'Components', 'Responsive Utilities'],
  },
  {
    id: 'web-performance',
    slug: 'web-performance',
    title: 'Web Performance Optimization',
    description: 'Optimize web applications with lazy loading, code splitting, caching strategies, and performance metrics.',
    category: 'Frontend Development',
    categorySlug: 'frontend',
    level: 'Advanced',
    duration: '8 hours',
    lessons: 40,
    projects: 2,
    rating: 4.8,
    reviews: 760,
    students: 15430,
    instructor: 'Tom Wilson',
    image: '/images/courses/performance.jpg',
    tags: ['Performance', 'Optimization', 'Caching'],
    topics: ['Optimization', 'Lazy Loading', 'Code Splitting', 'Caching Strategies'],
  },

  // Backend Development (9 courses)
  {
    id: 'nodejs-fundamentals',
    slug: 'nodejs-fundamentals',
    title: 'Node.js Fundamentals',
    description: 'Master Node.js event loop, modules, file system, streams, and buffer for server-side JavaScript.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '12 hours',
    lessons: 60,
    projects: 4,
    rating: 4.8,
    reviews: 2890,
    students: 52340,
    instructor: 'James Miller',
    image: '/images/courses/nodejs.jpg',
    tags: ['Node.js', 'Server-Side', 'JavaScript'],
    topics: ['Event Loop', 'Modules', 'File System', 'Streams', 'Buffer'],
    featured: true,
  },
  {
    id: 'expressjs-apis',
    slug: 'expressjs-apis',
    title: 'Express.js RESTful APIs',
    description: 'Build robust REST APIs with Express.js routing, middleware, authentication, and best practices.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.8,
    reviews: 1780,
    students: 38900,
    instructor: 'Maria Garcia',
    image: '/images/courses/express.jpg',
    tags: ['Express.js', 'REST APIs', 'Middleware'],
    topics: ['Routing', 'Middleware', 'RESTful APIs', 'Authentication'],
  },
  {
    id: 'python-fundamentals',
    slug: 'python-fundamentals',
    title: 'Python Programming',
    description: 'Learn Python fundamentals, OOP, data structures, file handling, and practical programming skills.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Beginner',
    duration: '14 hours',
    lessons: 70,
    projects: 5,
    rating: 4.9,
    reviews: 4560,
    students: 89760,
    instructor: 'Dr. Robert Lee',
    image: '/images/courses/python.jpg',
    tags: ['Python', 'OOP', 'Programming'],
    topics: ['Fundamentals', 'OOP', 'Data Structures', 'File Handling'],
    featured: true,
  },
  {
    id: 'django-web',
    slug: 'django-web',
    title: 'Django Web Development',
    description: 'Build web applications with Django MVT architecture, ORM, authentication, and REST framework.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 80,
    projects: 4,
    rating: 4.7,
    reviews: 1450,
    students: 28900,
    instructor: 'Sophie Martin',
    image: '/images/courses/django.jpg',
    tags: ['Django', 'Python', 'Web Framework'],
    topics: ['MVT Architecture', 'ORM', 'Authentication', 'REST Framework'],
  },
  {
    id: 'flask-web',
    slug: 'flask-web',
    title: 'Flask Web Applications',
    description: 'Create lightweight web apps with Flask routing, templates, extensions, and microservices.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.6,
    reviews: 890,
    students: 18760,
    instructor: 'Kevin White',
    image: '/images/courses/flask.jpg',
    tags: ['Flask', 'Python', 'Microservices'],
    topics: ['Routing', 'Templates', 'Extensions'],
  },
  {
    id: 'php-development',
    slug: 'php-development',
    title: 'PHP Server-Side Development',
    description: 'Master PHP server-side scripting, forms, sessions, cookies, and database integration.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Beginner',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.5,
    reviews: 780,
    students: 16540,
    instructor: 'Paul Johnson',
    image: '/images/courses/php.jpg',
    tags: ['PHP', 'Server-Side', 'Sessions'],
    topics: ['Server-Side Scripting', 'Forms', 'Sessions', 'Cookies'],
  },
  {
    id: 'ruby-rails',
    slug: 'ruby-rails',
    title: 'Ruby on Rails',
    description: 'Build web applications with Rails MVC pattern, Active Record, scaffolding, and best practices.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 65,
    projects: 4,
    rating: 4.6,
    reviews: 670,
    students: 14320,
    instructor: 'Anna Schmidt',
    image: '/images/courses/rails.jpg',
    tags: ['Ruby', 'Rails', 'MVC'],
    topics: ['MVC Pattern', 'Active Record', 'Scaffolding'],
  },
  {
    id: 'java-spring',
    slug: 'java-spring',
    title: 'Java & Spring Boot',
    description: 'Learn Java OOP, collections, multithreading, and Spring Boot basics for enterprise applications.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '18 hours',
    lessons: 90,
    projects: 5,
    rating: 4.7,
    reviews: 1230,
    students: 26780,
    instructor: 'Dr. Michael Chen',
    image: '/images/courses/java.jpg',
    tags: ['Java', 'Spring Boot', 'Enterprise'],
    topics: ['OOP', 'Collections', 'Multithreading', 'Spring Boot'],
  },
  {
    id: 'csharp-dotnet',
    slug: 'csharp-dotnet',
    title: 'C# & .NET Development',
    description: 'Master C# .NET fundamentals, ASP.NET Core, Entity Framework, and modern web development.',
    category: 'Backend Development',
    categorySlug: 'backend',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 75,
    projects: 4,
    rating: 4.7,
    reviews: 980,
    students: 21340,
    instructor: 'Steve Roberts',
    image: '/images/courses/csharp.jpg',
    tags: ['C#', '.NET', 'ASP.NET'],
    topics: ['.NET Fundamentals', 'ASP.NET Core', 'Entity Framework'],
  },

  // Database Technologies (7 courses)
  {
    id: 'sql-fundamentals',
    slug: 'sql-fundamentals',
    title: 'SQL Fundamentals',
    description: 'Master SQL queries, joins, indexes, normalization, and database design principles.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Beginner',
    duration: '8 hours',
    lessons: 45,
    projects: 3,
    rating: 4.9,
    reviews: 3450,
    students: 67890,
    instructor: 'Dr. Emily Davis',
    image: '/images/courses/sql.jpg',
    tags: ['SQL', 'Database', 'Queries'],
    topics: ['Queries', 'Joins', 'Indexes', 'Normalization'],
    featured: true,
  },
  {
    id: 'postgresql-advanced',
    slug: 'postgresql-advanced',
    title: 'PostgreSQL Advanced',
    description: 'Advanced PostgreSQL queries, JSON support, performance tuning, and database optimization.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Advanced',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.8,
    reviews: 890,
    students: 18760,
    instructor: 'Daniel Brown',
    image: '/images/courses/postgresql.jpg',
    tags: ['PostgreSQL', 'Performance', 'JSON'],
    topics: ['Advanced Queries', 'JSON Support', 'Performance Tuning'],
  },
  {
    id: 'mysql-complete',
    slug: 'mysql-complete',
    title: 'MySQL Database Design',
    description: 'Learn MySQL database design, stored procedures, triggers, and administration.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Intermediate',
    duration: '9 hours',
    lessons: 45,
    projects: 3,
    rating: 4.6,
    reviews: 1120,
    students: 24560,
    instructor: 'Laura Wilson',
    image: '/images/courses/mysql.jpg',
    tags: ['MySQL', 'Database Design', 'Procedures'],
    topics: ['Database Design', 'Stored Procedures', 'Triggers'],
  },
  {
    id: 'mongodb-nosql',
    slug: 'mongodb-nosql',
    title: 'MongoDB NoSQL',
    description: 'Master MongoDB document databases, aggregation pipelines, indexing, and schema design.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.8,
    reviews: 1560,
    students: 32340,
    instructor: 'Ryan Cooper',
    image: '/images/courses/mongodb.jpg',
    tags: ['MongoDB', 'NoSQL', 'Aggregation'],
    topics: ['NoSQL', 'Document Databases', 'Aggregation', 'Indexing'],
  },
  {
    id: 'redis-caching',
    slug: 'redis-caching',
    title: 'Redis Caching & Sessions',
    description: 'Implement Redis for caching, session storage, pub/sub patterns, and real-time data.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Intermediate',
    duration: '6 hours',
    lessons: 30,
    projects: 2,
    rating: 4.7,
    reviews: 670,
    students: 14320,
    instructor: 'Jessica Lee',
    image: '/images/courses/redis.jpg',
    tags: ['Redis', 'Caching', 'Pub/Sub'],
    topics: ['Caching', 'Session Storage', 'Pub/Sub'],
  },
  {
    id: 'firebase-backend',
    slug: 'firebase-backend',
    title: 'Firebase Backend Services',
    description: 'Build with Firebase realtime database, Firestore, authentication, and cloud functions.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Beginner',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.8,
    reviews: 1890,
    students: 38900,
    instructor: 'Mark Thompson',
    image: '/images/courses/firebase.jpg',
    tags: ['Firebase', 'Realtime', 'Firestore'],
    topics: ['Realtime Database', 'Firestore', 'Authentication'],
  },
  {
    id: 'graphql-apis',
    slug: 'graphql-apis',
    title: 'GraphQL API Development',
    description: 'Design GraphQL schemas, write queries, mutations, and build with Apollo Server.',
    category: 'Database Technologies',
    categorySlug: 'database',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.7,
    reviews: 1230,
    students: 26780,
    instructor: 'Chris Martinez',
    image: '/images/courses/graphql.jpg',
    tags: ['GraphQL', 'Apollo', 'APIs'],
    topics: ['Schema Design', 'Queries', 'Mutations', 'Apollo'],
  },

  // Blockchain & Web3 Development (11 courses)
  {
    id: 'solidity-smart-contracts',
    slug: 'solidity-smart-contracts',
    title: 'Solidity Smart Contracts',
    description: 'Write secure smart contracts with Solidity, understand EVM, gas optimization, and security patterns.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 80,
    projects: 5,
    rating: 4.9,
    reviews: 2340,
    students: 45230,
    instructor: 'Dr. Vitalik Chen',
    image: '/images/courses/solidity.jpg',
    tags: ['Solidity', 'Smart Contracts', 'EVM'],
    topics: ['Smart Contracts', 'EVM', 'Gas Optimization', 'Security Patterns'],
    featured: true,
  },
  {
    id: 'ethereum-development',
    slug: 'ethereum-development',
    title: 'Ethereum DApp Development',
    description: 'Build decentralized applications with Web3.js, Ethers.js, and integrate with Ethereum network.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 70,
    projects: 4,
    rating: 4.8,
    reviews: 1890,
    students: 38900,
    instructor: 'Sarah Blockchain',
    image: '/images/courses/ethereum.jpg',
    tags: ['Ethereum', 'Web3.js', 'DApps'],
    topics: ['Web3.js', 'Ethers.js', 'DApp Development'],
    featured: true,
  },
  {
    id: 'celo-blockchain',
    slug: 'celo-blockchain',
    title: 'Celo Blockchain Development',
    description: 'Learn Celo-specific features, mobile-first DeFi, Celo SDK, and stablecoin integration.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '12 hours',
    lessons: 60,
    projects: 4,
    rating: 4.8,
    reviews: 980,
    students: 21340,
    instructor: 'Marcus Celo',
    image: '/images/courses/celo.jpg',
    tags: ['Celo', 'Mobile DeFi', 'Stablecoins'],
    topics: ['Celo Features', 'Mobile-First DeFi', 'Celo SDK'],
  },
  {
    id: 'smart-contract-security',
    slug: 'smart-contract-security',
    title: 'Smart Contract Security',
    description: 'Identify vulnerabilities, perform audits, and implement security best practices for smart contracts.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Advanced',
    duration: '12 hours',
    lessons: 55,
    projects: 3,
    rating: 4.9,
    reviews: 1120,
    students: 24560,
    instructor: 'Dr. Security Expert',
    image: '/images/courses/security.jpg',
    tags: ['Security', 'Auditing', 'Vulnerabilities'],
    topics: ['Common Vulnerabilities', 'Auditing', 'Best Practices'],
  },
  {
    id: 'hardhat-development',
    slug: 'hardhat-development',
    title: 'Hardhat Development Environment',
    description: 'Set up Hardhat for smart contract development, testing, deployment, and debugging.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.8,
    reviews: 890,
    students: 19870,
    instructor: 'Dev Builder',
    image: '/images/courses/hardhat.jpg',
    tags: ['Hardhat', 'Testing', 'Deployment'],
    topics: ['Development Environment', 'Testing', 'Deployment'],
  },
  {
    id: 'truffle-suite',
    slug: 'truffle-suite',
    title: 'Truffle Suite Complete',
    description: 'Master Truffle for contract compilation, migration, testing, and Ganache local development.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.6,
    reviews: 670,
    students: 14320,
    instructor: 'Truffle Master',
    image: '/images/courses/truffle.jpg',
    tags: ['Truffle', 'Ganache', 'Migration'],
    topics: ['Contract Compilation', 'Migration', 'Testing'],
  },
  {
    id: 'web3-frontend',
    slug: 'web3-frontend',
    title: 'Web3 Frontend Integration',
    description: 'Connect wallets, interact with smart contracts, and build Web3-enabled user interfaces.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 4,
    rating: 4.8,
    reviews: 1560,
    students: 32340,
    instructor: 'Frontend Web3',
    image: '/images/courses/web3-frontend.jpg',
    tags: ['Web3', 'Wallets', 'Frontend'],
    topics: ['Wallet Connection', 'Contract Interaction'],
  },
  {
    id: 'defi-protocols',
    slug: 'defi-protocols',
    title: 'DeFi Protocol Development',
    description: 'Build DeFi applications including lending protocols, DEXs, staking, and liquidity pools.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Advanced',
    duration: '18 hours',
    lessons: 85,
    projects: 5,
    rating: 4.9,
    reviews: 1230,
    students: 26780,
    instructor: 'DeFi Expert',
    image: '/images/courses/defi.jpg',
    tags: ['DeFi', 'Lending', 'DEX', 'Staking'],
    topics: ['Lending', 'DEXs', 'Staking', 'Liquidity Pools'],
    featured: true,
  },
  {
    id: 'nft-development',
    slug: 'nft-development',
    title: 'NFT Development',
    description: 'Create NFTs with ERC-721, ERC-1155 standards, metadata management, and marketplace integration.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '12 hours',
    lessons: 55,
    projects: 4,
    rating: 4.8,
    reviews: 1780,
    students: 36540,
    instructor: 'NFT Creator',
    image: '/images/courses/nft.jpg',
    tags: ['NFT', 'ERC-721', 'Marketplaces'],
    topics: ['ERC-721', 'ERC-1155', 'Metadata', 'Marketplaces'],
  },
  {
    id: 'ipfs-storage',
    slug: 'ipfs-storage',
    title: 'IPFS Decentralized Storage',
    description: 'Implement IPFS for decentralized storage, pinning services, and DApp integration.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Intermediate',
    duration: '6 hours',
    lessons: 30,
    projects: 2,
    rating: 4.7,
    reviews: 560,
    students: 12340,
    instructor: 'Storage Expert',
    image: '/images/courses/ipfs.jpg',
    tags: ['IPFS', 'Decentralized', 'Storage'],
    topics: ['Decentralized Storage', 'Pinning', 'Integration'],
  },
  {
    id: 'blockchain-fundamentals',
    slug: 'blockchain-fundamentals',
    title: 'Blockchain Fundamentals',
    description: 'Understand blockchain consensus mechanisms, cryptography, and distributed systems architecture.',
    category: 'Blockchain & Web3',
    categorySlug: 'blockchain',
    level: 'Beginner',
    duration: '10 hours',
    lessons: 50,
    projects: 2,
    rating: 4.9,
    reviews: 2890,
    students: 56780,
    instructor: 'Dr. Blockchain',
    image: '/images/courses/blockchain-basics.jpg',
    tags: ['Blockchain', 'Cryptography', 'Consensus'],
    topics: ['Consensus', 'Cryptography', 'Distributed Systems'],
    featured: true,
  },

  // Mobile Development (4 courses)
  {
    id: 'react-native',
    slug: 'react-native',
    title: 'React Native Mobile Apps',
    description: 'Build cross-platform mobile apps with React Native, native modules, and navigation.',
    category: 'Mobile Development',
    categorySlug: 'mobile',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 75,
    projects: 4,
    rating: 4.8,
    reviews: 1890,
    students: 38900,
    instructor: 'Mobile Dev Expert',
    image: '/images/courses/react-native.jpg',
    tags: ['React Native', 'Mobile', 'Cross-Platform'],
    topics: ['Cross-Platform Development', 'Native Modules', 'Navigation'],
  },
  {
    id: 'flutter-development',
    slug: 'flutter-development',
    title: 'Flutter Development',
    description: 'Create beautiful mobile apps with Flutter, Dart language, widgets, and state management.',
    category: 'Mobile Development',
    categorySlug: 'mobile',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 70,
    projects: 4,
    rating: 4.8,
    reviews: 1560,
    students: 32340,
    instructor: 'Flutter Master',
    image: '/images/courses/flutter.jpg',
    tags: ['Flutter', 'Dart', 'Widgets'],
    topics: ['Dart Language', 'Widgets', 'State Management', 'Platform Integration'],
  },
  {
    id: 'ios-swift',
    slug: 'ios-swift',
    title: 'iOS Development with Swift',
    description: 'Build iOS apps with Swift, UIKit, SwiftUI, Core Data, and networking.',
    category: 'Mobile Development',
    categorySlug: 'mobile',
    level: 'Intermediate',
    duration: '18 hours',
    lessons: 85,
    projects: 5,
    rating: 4.7,
    reviews: 1120,
    students: 24560,
    instructor: 'iOS Expert',
    image: '/images/courses/ios.jpg',
    tags: ['iOS', 'Swift', 'SwiftUI'],
    topics: ['UIKit', 'SwiftUI', 'Core Data', 'Networking'],
  },
  {
    id: 'android-kotlin',
    slug: 'android-kotlin',
    title: 'Android Development with Kotlin',
    description: 'Build Android apps with Kotlin, activities, fragments, Room database, and Jetpack.',
    category: 'Mobile Development',
    categorySlug: 'mobile',
    level: 'Intermediate',
    duration: '18 hours',
    lessons: 85,
    projects: 5,
    rating: 4.7,
    reviews: 980,
    students: 21340,
    instructor: 'Android Expert',
    image: '/images/courses/android.jpg',
    tags: ['Android', 'Kotlin', 'Jetpack'],
    topics: ['Activities', 'Fragments', 'Room Database', 'Jetpack'],
  },

  // DevOps & Cloud (9 courses)
  {
    id: 'git-github',
    slug: 'git-github',
    title: 'Git & GitHub Mastery',
    description: 'Master version control with Git, branching strategies, pull requests, and CI/CD workflows.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Beginner',
    duration: '6 hours',
    lessons: 35,
    projects: 2,
    rating: 4.9,
    reviews: 4560,
    students: 89760,
    instructor: 'Git Master',
    image: '/images/courses/git.jpg',
    tags: ['Git', 'GitHub', 'Version Control'],
    topics: ['Version Control', 'Branching', 'Pull Requests', 'CI/CD'],
    featured: true,
  },
  {
    id: 'docker-containers',
    slug: 'docker-containers',
    title: 'Docker Containerization',
    description: 'Learn Docker containers, images, Docker Compose, and container orchestration basics.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.8,
    reviews: 1890,
    students: 38900,
    instructor: 'DevOps Pro',
    image: '/images/courses/docker.jpg',
    tags: ['Docker', 'Containers', 'DevOps'],
    topics: ['Containerization', 'Images', 'Docker Compose', 'Orchestration'],
  },
  {
    id: 'kubernetes',
    slug: 'kubernetes',
    title: 'Kubernetes Orchestration',
    description: 'Deploy and manage containerized applications with Kubernetes, deployments, and services.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Advanced',
    duration: '14 hours',
    lessons: 65,
    projects: 4,
    rating: 4.7,
    reviews: 980,
    students: 21340,
    instructor: 'K8s Expert',
    image: '/images/courses/kubernetes.jpg',
    tags: ['Kubernetes', 'K8s', 'Orchestration'],
    topics: ['Container Orchestration', 'Deployments', 'Services'],
  },
  {
    id: 'aws-cloud',
    slug: 'aws-cloud',
    title: 'AWS Cloud Services',
    description: 'Build on AWS with EC2, S3, Lambda, RDS, CloudFront, and serverless architectures.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 75,
    projects: 4,
    rating: 4.8,
    reviews: 2340,
    students: 45230,
    instructor: 'AWS Expert',
    image: '/images/courses/aws.jpg',
    tags: ['AWS', 'Cloud', 'Serverless'],
    topics: ['EC2', 'S3', 'Lambda', 'RDS', 'CloudFront'],
    featured: true,
  },
  {
    id: 'gcp-cloud',
    slug: 'gcp-cloud',
    title: 'Google Cloud Platform',
    description: 'Learn GCP with Compute Engine, Cloud Storage, Cloud Functions, and BigQuery.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 65,
    projects: 3,
    rating: 4.7,
    reviews: 890,
    students: 18760,
    instructor: 'GCP Pro',
    image: '/images/courses/gcp.jpg',
    tags: ['GCP', 'Google Cloud', 'BigQuery'],
    topics: ['Compute Engine', 'Cloud Storage', 'Cloud Functions'],
  },
  {
    id: 'azure-cloud',
    slug: 'azure-cloud',
    title: 'Microsoft Azure',
    description: 'Build with Azure Virtual Machines, App Services, Azure Functions, and DevOps tools.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 65,
    projects: 3,
    rating: 4.7,
    reviews: 780,
    students: 16540,
    instructor: 'Azure Expert',
    image: '/images/courses/azure.jpg',
    tags: ['Azure', 'Microsoft', 'Cloud'],
    topics: ['Virtual Machines', 'App Services', 'Azure Functions'],
  },
  {
    id: 'cicd-pipelines',
    slug: 'cicd-pipelines',
    title: 'CI/CD Pipelines',
    description: 'Automate deployments with GitHub Actions, Jenkins, GitLab CI, and DevOps practices.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.8,
    reviews: 1120,
    students: 24560,
    instructor: 'CI/CD Master',
    image: '/images/courses/cicd.jpg',
    tags: ['CI/CD', 'GitHub Actions', 'Jenkins'],
    topics: ['GitHub Actions', 'Jenkins', 'GitLab CI'],
  },
  {
    id: 'linux-cli',
    slug: 'linux-cli',
    title: 'Linux Command Line',
    description: 'Master Linux shell scripting, system administration, and command line tools.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Beginner',
    duration: '8 hours',
    lessons: 45,
    projects: 2,
    rating: 4.8,
    reviews: 2890,
    students: 56780,
    instructor: 'Linux Guru',
    image: '/images/courses/linux.jpg',
    tags: ['Linux', 'CLI', 'Shell'],
    topics: ['Shell Scripting', 'System Administration'],
  },
  {
    id: 'nginx-server',
    slug: 'nginx-server',
    title: 'Nginx Web Server',
    description: 'Configure Nginx web server, reverse proxy, load balancing, and SSL/TLS setup.',
    category: 'DevOps & Cloud',
    categorySlug: 'devops',
    level: 'Intermediate',
    duration: '6 hours',
    lessons: 30,
    projects: 2,
    rating: 4.7,
    reviews: 670,
    students: 14320,
    instructor: 'Server Admin',
    image: '/images/courses/nginx.jpg',
    tags: ['Nginx', 'Web Server', 'Load Balancing'],
    topics: ['Web Server Configuration', 'Reverse Proxy', 'Load Balancing'],
  },

  // Data Science & AI (5 courses)
  {
    id: 'python-data-science',
    slug: 'python-data-science',
    title: 'Python for Data Science',
    description: 'Analyze data with Python, NumPy, Pandas, Matplotlib, and Seaborn visualization.',
    category: 'Data Science & AI',
    categorySlug: 'data-science',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 70,
    projects: 4,
    rating: 4.9,
    reviews: 2340,
    students: 45230,
    instructor: 'Data Scientist',
    image: '/images/courses/data-science.jpg',
    tags: ['Python', 'NumPy', 'Pandas'],
    topics: ['NumPy', 'Pandas', 'Matplotlib', 'Seaborn'],
    featured: true,
  },
  {
    id: 'machine-learning',
    slug: 'machine-learning',
    title: 'Machine Learning',
    description: 'Build ML models with Scikit-learn, supervised and unsupervised learning algorithms.',
    category: 'Data Science & AI',
    categorySlug: 'data-science',
    level: 'Advanced',
    duration: '18 hours',
    lessons: 85,
    projects: 5,
    rating: 4.8,
    reviews: 1560,
    students: 32340,
    instructor: 'ML Expert',
    image: '/images/courses/ml.jpg',
    tags: ['Machine Learning', 'Scikit-learn', 'Algorithms'],
    topics: ['Scikit-learn', 'Supervised Learning', 'Unsupervised Learning'],
  },
  {
    id: 'deep-learning',
    slug: 'deep-learning',
    title: 'Deep Learning',
    description: 'Create neural networks with TensorFlow, PyTorch, CNNs, and RNNs for complex AI tasks.',
    category: 'Data Science & AI',
    categorySlug: 'data-science',
    level: 'Advanced',
    duration: '20 hours',
    lessons: 90,
    projects: 5,
    rating: 4.8,
    reviews: 1120,
    students: 24560,
    instructor: 'AI Researcher',
    image: '/images/courses/deep-learning.jpg',
    tags: ['Deep Learning', 'TensorFlow', 'PyTorch'],
    topics: ['TensorFlow', 'PyTorch', 'Neural Networks'],
  },
  {
    id: 'nlp',
    slug: 'nlp',
    title: 'Natural Language Processing',
    description: 'Process text with NLP techniques, sentiment analysis, and text classification.',
    category: 'Data Science & AI',
    categorySlug: 'data-science',
    level: 'Advanced',
    duration: '12 hours',
    lessons: 55,
    projects: 3,
    rating: 4.7,
    reviews: 780,
    students: 16540,
    instructor: 'NLP Specialist',
    image: '/images/courses/nlp.jpg',
    tags: ['NLP', 'Text Processing', 'Sentiment'],
    topics: ['Text Processing', 'Sentiment Analysis'],
  },
  {
    id: 'data-visualization',
    slug: 'data-visualization',
    title: 'Data Visualization',
    description: 'Create compelling visualizations with Tableau, Power BI, and D3.js for data storytelling.',
    category: 'Data Science & AI',
    categorySlug: 'data-science',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.7,
    reviews: 890,
    students: 18760,
    instructor: 'Viz Expert',
    image: '/images/courses/visualization.jpg',
    tags: ['Tableau', 'Power BI', 'D3.js'],
    topics: ['Tableau', 'Power BI', 'D3.js'],
  },

  // Programming Fundamentals (6 courses)
  {
    id: 'data-structures',
    slug: 'data-structures',
    title: 'Data Structures',
    description: 'Master arrays, linked lists, trees, graphs, and hash tables for efficient programming.',
    category: 'Programming Fundamentals',
    categorySlug: 'fundamentals',
    level: 'Intermediate',
    duration: '14 hours',
    lessons: 70,
    projects: 4,
    rating: 4.9,
    reviews: 3450,
    students: 67890,
    instructor: 'CS Professor',
    image: '/images/courses/data-structures.jpg',
    tags: ['Data Structures', 'Arrays', 'Trees'],
    topics: ['Arrays', 'Linked Lists', 'Trees', 'Graphs', 'Hash Tables'],
    featured: true,
  },
  {
    id: 'algorithms',
    slug: 'algorithms',
    title: 'Algorithms',
    description: 'Learn sorting, searching, dynamic programming, and recursion for optimal solutions.',
    category: 'Programming Fundamentals',
    categorySlug: 'fundamentals',
    level: 'Intermediate',
    duration: '16 hours',
    lessons: 75,
    projects: 4,
    rating: 4.9,
    reviews: 2890,
    students: 56780,
    instructor: 'Algorithm Expert',
    image: '/images/courses/algorithms.jpg',
    tags: ['Algorithms', 'Sorting', 'Dynamic Programming'],
    topics: ['Sorting', 'Searching', 'Dynamic Programming', 'Recursion'],
  },
  {
    id: 'oop',
    slug: 'oop',
    title: 'Object-Oriented Programming',
    description: 'Understand OOP principles: classes, inheritance, polymorphism, and encapsulation.',
    category: 'Programming Fundamentals',
    categorySlug: 'fundamentals',
    level: 'Beginner',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.8,
    reviews: 2340,
    students: 45230,
    instructor: 'OOP Master',
    image: '/images/courses/oop.jpg',
    tags: ['OOP', 'Classes', 'Inheritance'],
    topics: ['Classes', 'Inheritance', 'Polymorphism', 'Encapsulation'],
  },
  {
    id: 'functional-programming',
    slug: 'functional-programming',
    title: 'Functional Programming',
    description: 'Learn pure functions, immutability, higher-order functions, and functional patterns.',
    category: 'Programming Fundamentals',
    categorySlug: 'fundamentals',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 2,
    rating: 4.7,
    reviews: 780,
    students: 16540,
    instructor: 'FP Expert',
    image: '/images/courses/fp.jpg',
    tags: ['Functional', 'Pure Functions', 'Immutability'],
    topics: ['Pure Functions', 'Immutability', 'Higher-Order Functions'],
  },
  {
    id: 'design-patterns',
    slug: 'design-patterns',
    title: 'Design Patterns',
    description: 'Apply Singleton, Factory, Observer, MVC, and MVVM patterns in real applications.',
    category: 'Programming Fundamentals',
    categorySlug: 'fundamentals',
    level: 'Intermediate',
    duration: '12 hours',
    lessons: 55,
    projects: 3,
    rating: 4.8,
    reviews: 1120,
    students: 24560,
    instructor: 'Pattern Master',
    image: '/images/courses/patterns.jpg',
    tags: ['Design Patterns', 'MVC', 'MVVM'],
    topics: ['Singleton', 'Factory', 'Observer', 'MVC', 'MVVM'],
  },
  {
    id: 'system-design',
    slug: 'system-design',
    title: 'System Design',
    description: 'Design scalable systems with microservices, API design, and caching strategies.',
    category: 'Programming Fundamentals',
    categorySlug: 'fundamentals',
    level: 'Advanced',
    duration: '14 hours',
    lessons: 65,
    projects: 3,
    rating: 4.9,
    reviews: 1560,
    students: 32340,
    instructor: 'System Architect',
    image: '/images/courses/system-design.jpg',
    tags: ['System Design', 'Scalability', 'Microservices'],
    topics: ['Scalability', 'Microservices', 'API Design', 'Caching Strategies'],
  },

  // Testing & Quality Assurance (4 courses)
  {
    id: 'unit-testing',
    slug: 'unit-testing',
    title: 'Unit Testing',
    description: 'Write unit tests with Jest, Mocha, PyTest, and JUnit for reliable code.',
    category: 'Testing & QA',
    categorySlug: 'testing',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.8,
    reviews: 1230,
    students: 26780,
    instructor: 'Test Expert',
    image: '/images/courses/unit-testing.jpg',
    tags: ['Unit Testing', 'Jest', 'Mocha'],
    topics: ['Jest', 'Mocha', 'PyTest', 'JUnit'],
  },
  {
    id: 'integration-testing',
    slug: 'integration-testing',
    title: 'Integration Testing',
    description: 'Test APIs and integrations with Supertest, Cypress, and Selenium.',
    category: 'Testing & QA',
    categorySlug: 'testing',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.7,
    reviews: 780,
    students: 16540,
    instructor: 'QA Lead',
    image: '/images/courses/integration-testing.jpg',
    tags: ['Integration Testing', 'Cypress', 'Selenium'],
    topics: ['Supertest', 'Cypress', 'Selenium'],
  },
  {
    id: 'tdd',
    slug: 'tdd',
    title: 'Test-Driven Development',
    description: 'Practice TDD with red-green-refactor cycle and build robust software.',
    category: 'Testing & QA',
    categorySlug: 'testing',
    level: 'Intermediate',
    duration: '6 hours',
    lessons: 30,
    projects: 2,
    rating: 4.8,
    reviews: 670,
    students: 14320,
    instructor: 'TDD Advocate',
    image: '/images/courses/tdd.jpg',
    tags: ['TDD', 'Red-Green-Refactor', 'Testing'],
    topics: ['Red-Green-Refactor Cycle'],
  },
  {
    id: 'e2e-testing',
    slug: 'e2e-testing',
    title: 'End-to-End Testing',
    description: 'Automate browser testing with Playwright and Puppeteer for full coverage.',
    category: 'Testing & QA',
    categorySlug: 'testing',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.7,
    reviews: 560,
    students: 12340,
    instructor: 'E2E Expert',
    image: '/images/courses/e2e.jpg',
    tags: ['E2E Testing', 'Playwright', 'Puppeteer'],
    topics: ['Playwright', 'Puppeteer'],
  },

  // Specialized Skills (8 courses)
  {
    id: 'restful-api-design',
    slug: 'restful-api-design',
    title: 'RESTful API Design',
    description: 'Design REST APIs with best practices, versioning, documentation, and OpenAPI.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 3,
    rating: 4.8,
    reviews: 1560,
    students: 32340,
    instructor: 'API Expert',
    image: '/images/courses/rest-api.jpg',
    tags: ['REST', 'API Design', 'OpenAPI'],
    topics: ['Best Practices', 'Versioning', 'Documentation'],
  },
  {
    id: 'graphql-advanced',
    slug: 'graphql-advanced',
    title: 'GraphQL Advanced',
    description: 'Build GraphQL APIs with schema design, resolvers, subscriptions, and federation.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Advanced',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.8,
    reviews: 890,
    students: 18760,
    instructor: 'GraphQL Master',
    image: '/images/courses/graphql-advanced.jpg',
    tags: ['GraphQL', 'Subscriptions', 'Federation'],
    topics: ['Schema Design', 'Resolvers', 'Subscriptions'],
  },
  {
    id: 'websockets',
    slug: 'websockets',
    title: 'WebSockets & Real-Time',
    description: 'Build real-time applications with WebSockets and Socket.io.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Intermediate',
    duration: '6 hours',
    lessons: 30,
    projects: 2,
    rating: 4.7,
    reviews: 670,
    students: 14320,
    instructor: 'Real-Time Dev',
    image: '/images/courses/websockets.jpg',
    tags: ['WebSockets', 'Socket.io', 'Real-Time'],
    topics: ['Real-Time Communication', 'Socket.io'],
  },
  {
    id: 'microservices',
    slug: 'microservices',
    title: 'Microservices Architecture',
    description: 'Design microservices with service communication, API gateways, and event-driven patterns.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Advanced',
    duration: '14 hours',
    lessons: 65,
    projects: 4,
    rating: 4.8,
    reviews: 1120,
    students: 24560,
    instructor: 'Architect Expert',
    image: '/images/courses/microservices.jpg',
    tags: ['Microservices', 'API Gateway', 'Events'],
    topics: ['Service Communication', 'API Gateways'],
  },
  {
    id: 'pwa',
    slug: 'pwa',
    title: 'Progressive Web Apps',
    description: 'Build PWAs with service workers, offline functionality, and push notifications.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Intermediate',
    duration: '8 hours',
    lessons: 40,
    projects: 2,
    rating: 4.7,
    reviews: 780,
    students: 16540,
    instructor: 'PWA Expert',
    image: '/images/courses/pwa.jpg',
    tags: ['PWA', 'Service Workers', 'Offline'],
    topics: ['Service Workers', 'Offline Functionality'],
  },
  {
    id: 'cybersecurity',
    slug: 'cybersecurity',
    title: 'Cybersecurity Basics',
    description: 'Learn authentication, authorization, encryption, and OWASP Top 10 vulnerabilities.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Intermediate',
    duration: '10 hours',
    lessons: 50,
    projects: 3,
    rating: 4.9,
    reviews: 1890,
    students: 38900,
    instructor: 'Security Expert',
    image: '/images/courses/cybersecurity.jpg',
    tags: ['Security', 'OWASP', 'Encryption'],
    topics: ['Authentication', 'Authorization', 'Encryption', 'OWASP Top 10'],
  },
  {
    id: 'agile-scrum',
    slug: 'agile-scrum',
    title: 'Agile & Scrum',
    description: 'Master agile methodologies with sprint planning, standups, and retrospectives.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Beginner',
    duration: '6 hours',
    lessons: 30,
    projects: 1,
    rating: 4.6,
    reviews: 1230,
    students: 26780,
    instructor: 'Scrum Master',
    image: '/images/courses/agile.jpg',
    tags: ['Agile', 'Scrum', 'Sprint Planning'],
    topics: ['Sprint Planning', 'Standups', 'Retrospectives'],
  },
  {
    id: 'technical-writing',
    slug: 'technical-writing',
    title: 'Technical Writing',
    description: 'Write clear documentation, README files, and API docs for developers.',
    category: 'Specialized Skills',
    categorySlug: 'specialized',
    level: 'Beginner',
    duration: '5 hours',
    lessons: 25,
    projects: 2,
    rating: 4.6,
    reviews: 560,
    students: 12340,
    instructor: 'Tech Writer',
    image: '/images/courses/tech-writing.jpg',
    tags: ['Documentation', 'README', 'API Docs'],
    topics: ['Documentation', 'README Files', 'API Docs'],
  },
];

export const getFeaturedCourses = (): Course[] => {
  return courses.filter(course => course.featured);
};

export const getCoursesByCategory = (categorySlug: string): Course[] => {
  return courses.filter(course => course.categorySlug === categorySlug);
};

export const getCourseBySlug = (slug: string): Course | undefined => {
  return courses.find(course => course.slug === slug);
};

export const searchCourses = (query: string): Course[] => {
  const lowercaseQuery = query.toLowerCase();
  return courses.filter(
    course =>
      course.title.toLowerCase().includes(lowercaseQuery) ||
      course.description.toLowerCase().includes(lowercaseQuery) ||
      course.tags.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
};

export const learningPaths = [
  {
    id: 'blockchain-developer',
    title: 'Blockchain Developer',
    description: 'Become a full-stack blockchain developer',
    courses: ['blockchain-fundamentals', 'solidity-smart-contracts', 'ethereum-development', 'defi-protocols', 'nft-development'],
    duration: '60 hours',
    level: 'Intermediate to Advanced',
  },
  {
    id: 'fullstack-web',
    title: 'Full-Stack Web Developer',
    description: 'Master both frontend and backend development',
    courses: ['html5-fundamentals', 'css3-mastery', 'javascript-es6-plus', 'react-complete', 'nodejs-fundamentals', 'mongodb-nosql'],
    duration: '70 hours',
    level: 'Beginner to Intermediate',
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    description: 'Learn data analysis and machine learning',
    courses: ['python-fundamentals', 'python-data-science', 'machine-learning', 'deep-learning', 'data-visualization'],
    duration: '65 hours',
    level: 'Intermediate to Advanced',
  },
];